# Generated by Django 2.2.3 on 2019-07-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_application_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='port',
        ),
    ]
