# Generated by Django 2.2.3 on 2019-07-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
