# Generated by Django 2.2.3 on 2019-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads')),
                ('desc', models.CharField(max_length=20)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(default=0, upload_to='gds'),
            preserve_default=False,
        ),
    ]
