# Generated by Django 2.2.3 on 2019-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_auto_20190716_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='colors',
            new_name='color',
        ),
        migrations.AddField(
            model_name='good',
            name='maximg',
            field=models.ImageField(default='dgs', upload_to='gds'),
        ),
    ]
