# Generated by Django 2.2.3 on 2019-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_auto_20190716_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='maximg',
            field=models.ImageField(upload_to='gds'),
        ),
    ]
