# Generated by Django 2.2.3 on 2019-07-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0006_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Order')),
            ],
        ),
    ]
