# Generated by Django 2.2.3 on 2019-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20190704_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('good', '好人'), ('bad', '坏人')], default='good', max_length=5),
        ),
    ]
