# Generated by Django 2.2.3 on 2019-07-08 05:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_heroinfo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='ads')),
            ],
        ),
        migrations.AlterModelManagers(
            name='heroinfo',
            managers=[
                ('myobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
